franmendonca/nomadity

app/models/experience.rb, app/models/user.rb, db/migrate/20220301120906_create_experiences.rb, test/models/experience_test.rb
added experience model and insert act as favoritable to it
=> added experience model and added to it act_as_favoritable

Gemfile, Gemfile.lock, app/models/favorite.rb, app/models/user.rb, config/initializers/acts_as_favoritor.rb, db/migrate/20220301120246_acts_as_favoritor_migration.rb, db/schema.rb
added act as favoridor gem to add the "like" feature
=> added act as favoridor gem and added to the model

app/controllers/categories_controller.rb, app/controllers/cities_controller.rb, test/controllers/categories_controller_test.rb, test/controllers/cities_controller_test.rb
Added categories and cities controllers with skeleton body (to do later)
=> added categories and cities controllers

app/controllers/experiences_controller.rb, test/controllers/experiences_controller_test.rb
created barebone experiences controller
=> added experiences controller

config/routes.rb
the title of the branch is wrong 😅
=> added profile route

app/controllers/pages_controller.rb, app/views/pages/profile.html.erb, config/routes.rb
added profile view and really fixed profile routes
=> Add profile view

app/controllers/favorites_controller.rb, app/views/experiences/show.html.erb, config/routes.rb
=> Unfavorite

app/views/experiences/show.html.erb, db/seeds.rb
Did 4 bespoke seeds and 10 instances per category. Still need to figure out address randomizer
=> finalized seeds

app/assets/stylesheets/components/_category.scss, app/assets/stylesheets/components/_index.scss, app/views/categories/index.html.erb, app/views/experiences/index.html.erb
Fixed the switch between categories and experiences page
=> fixed categories

app/views/experiences/show.html.erb, db/seeds.rb
Added longitude and latitude to seeds
=> finalized seeds with address long lat

app/assets/stylesheets/components/_experience_card.scss, app/assets/stylesheets/components/_index.scss, app/javascript/controllers/mapbox_controller.js, app/views/experiences/index.html.erb, app/views/shared/_experience_card.html.erb, app/views/shared/_mapbox.html.erb
=> basic experience card partial

app/views/shared/_experience_card.html.erb
got a heart on the experience card
=> created heart-favorite button but the link is wrong

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_show-modal.scss, app/views/experiences/index.html.erb, app/views/shared/_experience_card.html.erb, app/views/shared/_show_modal.html.erb, db/seeds.rb
=> added modal

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_home-card.scss, app/views/shared/_home-cards.html.erb, app/views/shared/_search.html.erb, db/seeds.rb
Added bio to user seed
Fixed home cards explanations of the app
=> added info and styling to home page

app/views/shared/_favorite_card.html.erb
fix right margin on profile cards
=> fixed margin on profile card

app/assets/stylesheets/components/_home-card.scss, app/views/shared/_profile_sidebar.html.erb
fix content in the home cards, now text is inside the card
=> Fix home cards

app/assets/stylesheets/components/_category.scss, app/views/categories/index.html.erb, db/seeds.rb
**added progress bar on category page for now**
=> add-progress-bar

app/controllers/favorites_controller.rb, app/javascript/controllers/favorites_controller.js, app/views/shared/_experience_card.html.erb, app/views/shared/_favorite_button.html.erb, config/routes.rb
made a favorite button did not work on the map
=> added favorite button

app/assets/stylesheets/application.scss
=> removed favorite partial

app/views/pages/profile.html.erb
Added modal to profile, still needs work to direct to specific experience
=> added modal to profile

app/assets/stylesheets/components/_category.scss, app/views/categories/index.html.erb, app/views/shared/_experience_card.html.erb, app/views/shared/_show_modal.html.erb
Added a favorite button to modal (still needs websocket)
Edited categories page
=> added favorite to modal

app/views/shared/_profile_sidebar.html.erb
=> profile picture

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_carousel.scss, app/assets/stylesheets/components/_category.scss, app/assets/stylesheets/components/_experience_card.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_home-card.scss, app/assets/stylesheets/components/_profile_sidebar.scss, app/assets/stylesheets/components/_scrollmenu.scss, app/assets/stylesheets/components/_search-form.scss, app/assets/stylesheets/components/_show-modal.scss, app/assets/stylesheets/config/_bootstrap_variables.scss, app/views/experiences/index.html.erb, app/views/pages/profile.html.erb, app/views/shared/_banner.html.erb, app/views/shared/_home-cards.html.erb, app/views/shared/_navbar.html.erb, app/views/shared/_search.html.erb, app/views/shared/_show_modal.html.erb
Edited search bar in main menu
Styled all pages with same border radius
Moved favorite button on modal page to top right
Changed margin of map on profile page
Edited cards on home page
Changed scrollable bar on experience list to match figma
Added more info to modal show card
Changed banner fonts 
Changed experience card shadows to match figma
Edited buttons to have similar border radius as other elements
=> added several style changes 

app/assets/stylesheets/application.scss, app/assets/stylesheets/components/_profile.scss, app/views/pages/profile.html.erb, app/views/shared/_profile_sidebar.html.erb
rounded corners in preferences buttons
one  more column to the map
=> [UI]few changes in profile page

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_experience_card.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_home-card.scss, app/assets/stylesheets/components/_navbar.scss, app/assets/stylesheets/components/_profile_sidebar.scss, app/views/shared/_experience_card.html.erb, app/views/shared/_footer.html.erb, app/views/shared/_home-cards.html.erb, app/views/shared/_navbar.html.erb, app/views/shared/_profile_sidebar.html.erb
Changed footer info and color
Changed heart on experience card to match figma
Changed show card pop up style color and text color
=> changed footer and added info

app/assets/stylesheets/components/_show-modal.scss, app/controllers/pages_controller.rb, app/views/experiences/show.html.erb, app/views/shared/_experience_card.html.erb, app/views/shared/_originalmodal.html.erb, app/views/shared/_show_modal.html.erb
carousel buttons aren't working properly
=> added a carousel with some bugs to fix

app/assets/stylesheets/components/_show-modal.scss, app/controllers/pages_controller.rb, app/views/experiences/show.html.erb, app/views/shared/_experience_card.html.erb, app/views/shared/_originalmodal.html.erb, app/views/shared/_show_modal.html.erb
=> Carousel bug fixed

app/views/categories/index.html.erb, db/seeds.rb
=> changed icon in the seed

app/controllers/favorites_controller.rb, app/views/shared/_show_modal.html.erb
get rid of heart in the modal page
=> removed heart from modal

app/views/shared/_show_modal.html.erb
=> removed heart on modal

app/controllers/experiences_controller.rb, app/javascript/controllers/mapbox_controller.js
**i see icons in mapbox.
you can see them all except con-work and nightlife**
=> icon-mapbox

app/javascript/controllers/mapbox_controller.js, app/views/pages/profile.html.erb, app/views/shared/_show_modal.html.erb
Fixed icons not showing
Fixed modal icons
=> fixed icons

app/javascript/controllers/mapbox_controller.js
=> upgrade-mapbox-new-icon

app/views/categories/index.html.erb, app/views/experiences/index.html.erb, app/views/pages/profile.html.erb, app/views/shared/_routes.html.erb
=> animated progress-bar

app/views/experiences/index.html.erb, app/views/shared/_show_modal.html.erb
**I added an icon to the website and put the text "website" and the link in one line.**
i put the bar exactly where it is on figma
=> add-img-web-&-fixed-text

app/assets/stylesheets/components/_category.scss, app/views/experiences/index.html.erb
**added text in result page as in figma before progress bar**
=> add-text-in-results-page

app/views/shared/_info_window.html.erb, app/views/shared/_show_modal.html.erb
=> info-window-mapbox-&-improved-show-card

app/views/shared/_banner.html.erb
=> new-banner

app/controllers/pages_controller.rb, app/javascript/controllers/directions_controller.js, app/views/pages/directions.html.erb, app/views/shared/_directions_mapbox.html.erb
new mapbox created for the directions page but still working on the routing function
=> new mapbox partial loaded on directions page

app/assets/stylesheets/components/_profile.scss, app/views/pages/profile.html.erb
=> Move Routes button inside the map

app/assets/stylesheets/components/_banner.scss
=> new-color-banner-H4

app/views/shared/_show_modal.html.erb
=> add-latitude-longitude-show-card

app/models/experience.rb, app/views/shared/_experience_card.html.erb, app/views/shared/_mapbox.html.erb
Added address to modal, experience and profile cards
=> added address

app/views/shared/_experience_card.html.erb
=> fix-seed-lisbon-results-page

app/javascript/controllers/directions_controller.js
=> added directions with multiple stops

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_progress-bar.scss, app/views/categories/index.html.erb, app/views/experiences/index.html.erb, app/views/pages/directions.html.erb, app/views/pages/home.html.erb, app/views/pages/profile.html.erb
=> upgrade-progress-bar

app/views/pages/directions.html.erb
" Go back" button in the direction page
=> added a go back button on direction page

app/views/experiences/index.html.erb
Added city name to experiences page index so it tells which city you are in
=> added city name to results page

app/assets/stylesheets/components/_experience_card.scss
Changed width of experience cards to match progress bar
=> changed width of cards to match progress bar

app/assets/stylesheets/components/_scrollmenu.scss, app/views/experiences/index.html.erb
=> enlarged categories slider on the exp page

app/assets/stylesheets/components/_banner.scss, app/assets/stylesheets/components/_category.scss, app/assets/stylesheets/components/_profile_sidebar.scss, app/assets/stylesheets/config/_fonts.scss, app/views/experiences/index.html.erb, app/views/shared/_profile_sidebar.html.erb, app/views/shared/_show_modal.html.erb
Fixed font size and colors to match figma more closely
=> Fix index profile fonts

app/views/pages/profile.html.erb
Reverts franmendonca/nomadity#128
=> Revert "fix stiky map"

app/javascript/controllers/directions_controller.js
=> upgrade-icons-in-directions-page

db/seeds.rb
Final seeds are done!
3 per category
No repeating photos on experience card,
No lorem ipsum
=> added final seeds

app/assets/stylesheets/components/_buttons.scss
Increased favorite button size to 20px
=> changed font size for favorite button

app/assets/stylesheets/components/_profile_sidebar.scss, app/views/shared/_profile_sidebar.html.erb
Fixed the padding on the preferences buttons
=> Fix preferences buttons

app/assets/stylesheets/components/_map.scss
Removed the search bar from the map
=> removed search box from map

app/views/shared/_profile_sidebar.html.erb
Removed bio from routes page, left preferences
=> removed bio

app/assets/stylesheets/components/_map.scss, app/assets/stylesheets/components/_scrollmenu.scss, app/views/experiences/index.html.erb
Added margin right to the address icon
Changed word-wrap to break to prevent words from coming out of the pop up
=> fixed word break and margin on popup

app/assets/stylesheets/components/_map.scss
Changed font size to 20 px,
Added margin right to the button
=> fixed button for closing pop up, margin and size

app/views/shared/_show_modal.html.erb
=> fixed the image repetition

app/views/experiences/index.html.erb, app/views/pages/profile.html.erb
slightly changed the wording in the instructions
=> slightly changed user instructions

app/assets/stylesheets/components/_category.scss, app/views/pages/directions.html.erb, app/views/pages/profile.html.erb
=> fixed margin on pages

app/assets/stylesheets/components/_experience_card.scss, app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_map.scss, app/assets/stylesheets/components/_profile.scss, app/assets/stylesheets/components/_scrollmenu.scss, app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/config/_colors.scss, app/javascript/controllers/categories_controller.js, app/views/experiences/index.html.erb
Edited mapbox height
Changed button shadows
Changed other shadows
Added js to active category
=> general styling and map editing
